version: '3.1'
services:

  nginx:
    container_name: con-nginx
    image: nginx:latest
    restart: always
    depends_on:
      - php
    links:
      - php
    volumes:
      - ./nginx/configs/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs/:/var/log/nginx/
      - ./work_dir/html/:/var/www/html/
    ports:
      - 80:80
      - 443:443

  php:
    container_name: con-php
    #image: php:8.2-fpm
    build:
      context: ./php/
    restart: always
    links:
      - mariadb
    volumes:
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./php/web.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./php/logs/:/usr/local/var/log/
      - ./work_dir/html/:/var/www/html/
      - ./work_dir/sessions/:/var/www/session/
    # UID:GID user for writing in work folder
    user: 1000:1000

  mariadb:
    container_name: con-mariadb
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: super
      MYSQL_DATABASE: test
      MYSQL_USER: web
      MYSQL_PASSWORD: super
    user: root:root
    volumes:
      - ./mysql/:/etc/mysql/conf.d/
      - ./mysql_backup/:/var/lib/
   
    
