version: '3.8'
services:

  nginx:
    container_name: con-nginx
    image: nginx:latest
    restart: always
    depends_on:
      - php
    links:
      - php
    volumes:
      - ./nginx/configs/default.nginx:/etc/nginx/conf.d/default.conf
      - ./nginx/logs/:/var/log/nginx/
      - ./work_dir/html/:/var/www/html/
    ports:
      - 80:80
      - 443:443

  php:
    container_name: con-php
    build:
      context: ./php/
    restart: always
    links:
      - mariadb
    volumes:
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./php/web.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./php/logs/:/usr/local/var/log/
      - ./work_dir/html/:/var/www/html/
      - ./work_dir/sessions/:/var/www/session/
    # UID:GID user for writing in work folder
    user: 1000:1000

  mariadb:
    container_name: con-mariadb
    image: mariadb:latest
    restart: always
    volumes:
      - ./mysql/backup:/var/lib/mysql
      - ./mysql/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: web
      MARIADB_PASSWORD: super
      MARIADB_DATABASE: test